development:
  host: "localhost"
  port: 6379

staging:
  host: "redis-staging.mykewldomain.biz"
  port: 6379

production:
  host: "redis.mykewldomain.biz"
  port: 6379

test:
  host: "localhost"
  port: 6379