development:
  host: localhost
  database: thin_connector_dev
  username:
  password:

test:
  host: localhost
  database: thin_connector_test
  username:
  password:

production:
  host: localhost
  database: thin_connector_prod
  username:
  password: